### ISSUE TITLE
Mitä tapahtuu kun kaikki URL-osoitteet on varattu?

### ISSUE THREAD

**Issue by nomelif** [felixbade/lyli-api#1]
Kun viimeinen osoite (jos sellainen on) on vqratty, kaatuuko serveri seuraavalla yrityksellä varata osoite?
    Entä jos joku kirjoittaa dos-tyyppisen skriptin, joka varaa kaikki osoitteet. Jos se käy ne kaikki läpi kerran päivässä, jäävätkö ne ikuisesti muistiin, jos osoite vapautuu kahden viikon kuluttua viimeisestä käytöstä?
    Jos vastaava ongelma tosiaan on, voisiko sanoa, että tietty kone saa varata vain tietyn määrän osoitteita? Tai n osoitetta ajassa t?
Terv. Theo Friberg

**Comment by nomelif** [comment]
Tai captchca osoitetta varatessa?

**Comment by felixbade** [comment]
Lyhyet linkit eivät lopu kesken. Tähän mennessä kaksikirjaimiset päätteet ovat riittäneet mainiosti, mutta palvelin siirtyy pidempiin automaattisesti.

Lyhyet linkit pysyvät ikuisesti muistissa, jos niitä käytetään joka päivä.

**Comment by nomelif** [comment]
Anteeksi, katsoin koodin kunnolla vasta äsken, enkä Flaskia paremmin tunne. Vaikka linkit eivät lopu kesken, niin tokkopa ne kovin lyhyinä pysyvät, jos jokin botti (tai -verkko) niitä silmukassa pyytää.

Osoittautuuko tallennustila ongelmaksi jos pyydetään tuhat linkkiä? Kymmenen tuhatta? Miljoona? Entä jos lyhennettävät linkit ovat pitkiä (google-haku)?

Tai tyyppiä https://kuinka-mones-varataan.com/hexadesimaaliroskaa/seuraavat/50000/merkkiä? Hyökkääjä voisi vaikka muuttaa 50gb tiedostoja linkiksi, jonka se uploadaa sivulle. Silloin serveri joutuisi säilyttämään 50gb roskaa / hyökkääjän omia tiedostoja. Linkin valiidiksi tarkistaminen tässä tilanteessa voidaan kiertää laittamalla domainksi jotakin järkevää. Kun osoitteen pituutta ei testata, on tämä täysin mahdollista.

Sitaatti http-standardista:

```
The HTTP protocol does not place any a priori limit on the length of
a URI. Servers MUST be able to handle the URI of any resource they serve, and SHOULD be able to 
handle URIs of unbounded length if they provide GET-based forms that could generate such URIs. A 
server SHOULD return 414 (Request-URI Too Long) status if a URI is longer than the server can handle (see section 10.4.15).

Note: Servers ought to be cautious about depending on URI lengths above 255 bytes, because some older client or proxy implementations might not properly support these lengths.
```

**Comment by felixbade** [comment]
Totta, pitkän linkin pituus pitäisi varmaan tarkistaa. Samoin lyhyen linkin päätteen pituus. Tuskin tarvitsee olla tukea yli 2000-merkkisille URLeille: http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Comment by felixbade** [comment]
En usko että miljoona linkkiä on ongelma, mutten ole testannut.

**Comment by nomelif** [comment]
Mitä mieltä olet captchcoista? Saatan ehkä lähettää patchin tms., jos taito riittää. Estäisi botteja rekisteröimästä urleja.

(Laskut voivat olla puutaheinää) Ja jos ajatellaan mahd. botin lähettävän pyyntöjä 50 / s, saa se vuorokaudessa 50 \* 60 \* 60 \* 24 = 4320000 osoitetta varattua ja pidettyä ne hengissä niin kauan kuin huvittaa. Osoitteet olisivat tuolloin ymmärtääkseni 5-6 merkkiä pikiä. Jos otetaan käyttöön suurempi määrä botteja, saadaan nopeasti aikaan huima määrä osoitteita.

Jos osoitteet ovat pituudeltaan 2000 merkkiä, syntyy dataa kuitenkin 4320000 \* 2000 = 8620000000 merkkiä eli jos osoitteet tallennetaan unicodena 8620000000 \* 8 = 68960000000 bittiä eli 68,96 gigabittiä. Lisäksi tulee tallentaa osoitteista vielä lyhennetyt versiot. Onko tähän varauduttu?

**Comment by felixbade** [comment]
Captchat hankaloittavat käyttöä enkä mielellään lisää semmoisia ellei ole pakko. Botit ovat ok, kunhan eivät floodaa. Minullakin on yksi (https://github.com/felixbade/Nux6).

En ole varautunut palvelunestohyökkäyksiin.

**Comment by nomelif** [comment]
Palvelun esto hän voisi torjua laittamalla captchca, mutta vain jos esim. viimeisten kymmenen sekunnin aikana on tullut 50 pyyntyöä. Sen ei pitäisi keskiverto käyttäjää liiemmin haitata.

**Comment by felixbade** [comment]
Mielummin laitan rajoituksen että esim tunnin aikana voi lyhentää vain sata linkkiä. Captchan kirjoittaminen hidastaa lyhentämistä liikaa, siihen pitäisi mennä vain pari sekuntia.
